-- String, format(), to_char/to_number, regex, encoding, escape errors.
SELECT format('%');
SELECT format('%z', 1);
SELECT format('%2$s');
SELECT format('%*s', 'x');
SELECT format('%1$', 1);
SELECT format('%I', NULL);
SELECT format('%L%');
SELECT to_number('abc', '999');
SELECT to_number('12', 'NONSENSE_ZZ');
SELECT to_number('', '');
SELECT to_char(123, 'RN');
SELECT to_char(1234, 'RN');
SELECT to_char(0, 'RN');
SELECT lpad('x', -2147483648, 'y');
SELECT rpad('x', 2000000000, 'yyyy');
SELECT repeat('x', 2000000000);
SELECT substring('abc' from 1 for -1);
SELECT substr('abc', 1, -5);
SELECT left('abc', -2147483648);
SELECT 'abc' || repeat('x', 1000000000) || repeat('y', 1000000000);
SELECT chr(-1);
SELECT chr(0);
SELECT chr(2000000000);
SELECT ascii('');
SELECT convert('x'::bytea, 'NOSUCH', 'UTF8');
SELECT convert_from('\xff'::bytea, 'UTF8');
SELECT convert_to('x', 'NOSUCH');
SELECT convert('abc'::bytea, 'UTF8', 'NOSUCH');
SELECT 'a'::text ~ '[';
SELECT 'a'::text ~ '(';
SELECT 'a'::text ~ '*';
SELECT 'a'::text ~ 'a{2,1}';
SELECT regexp_replace('a', '(', 'x');
SELECT regexp_match('a', '\y\z');
SELECT regexp_matches('a', 'a', 'Z');
SELECT regexp_split_to_array('a', '(');
SELECT regexp_count('a', '[');
SELECT regexp_substr('a', '[');
SELECT regexp_like('a', '[');
SELECT substring('abc' from '(');
SELECT similar_to_escape('a', 'aa');
SELECT 'a' SIMILAR TO 'a' ESCAPE 'aa';
SELECT 'a' LIKE 'a' ESCAPE 'aa';
SELECT translate('abc', 'a', '');
SELECT split_part('a,b', ',', 0);
SELECT quote_ident('');
SELECT unistr('\u');
SELECT unistr('\xZZ');
SELECT normalize('a', NOSUCH);
SELECT 'abc'::text COLLATE "nonexistent_collation";
SELECT encode('x'::bytea, 'base65');
SELECT parse_ident('1.2.3.', strict => true);
SELECT starts_with('a', 'b')::int / 0;
