-- Arrays, ranges, multiranges, composite/record errors.
SELECT ARRAY[1,2,3][5:1];
SELECT (ARRAY[1,2,3])[0];
SELECT array_fill(0, ARRAY[-1]);
SELECT array_fill(0, ARRAY[1,2], ARRAY[1]);
SELECT array_fill(0, ARRAY[2000000000, 2000000000]);
SELECT array_dims(ARRAY[[1,2],[3]]);
SELECT '[2:1]={}'::int[];
SELECT '{{1,2},{3}}'::int[];
SELECT '{1,2}'::int[] || '{{3,4}}'::int[];
SELECT ARRAY[1,2] || ARRAY[[3,4]];
SELECT array_cat('{1}'::int[], '{{2}}'::int[]);
SELECT array_position(ARRAY[[1,2]], 1);
SELECT array_agg(x) FROM (VALUES (ARRAY[1]),(ARRAY[1,2])) t(x);
SELECT unnest(ARRAY[1,2], ARRAY[3]) ;
SELECT array_upper(ARRAY[1], 0);
SELECT '{1,2,3}'::int[] # 5;
SELECT (ARRAY[1,2,3])[1:2][1];
SELECT array_length(ARRAY[1], -1);
SELECT int4range(5, 1);
SELECT int4range(1, 5, '(]')::text::int4range;
SELECT '[1,5)'::int4range * '[10,20)'::int4range - '[12,14)'::int4range;
SELECT numrange(1,10) + numrange(20,30);
SELECT range_merge(int4range(1,2), int4range(5,6)) - int4range(1,10);
SELECT lower(int4range(NULL, NULL));
SELECT int4range(1,2) * int4range(2,3);
SELECT '{[1,2],[5,6]}'::int4multirange @> 3;
SELECT '{[1,10)}'::int4multirange - '{[3,5)}'::int4multirange;
SELECT '{(,)}'::int4multirange + '{[1,2)}'::int4multirange;
SELECT '[a,b]'::numrange;
SELECT '(1,2,3)'::int4range;
SELECT '[1,]'::int4range::text::int8range;
SELECT ROW(1,2)::repro.parent;
SELECT ROW(1)::repro.parent;
SELECT ('1','x')::repro.parent;
SELECT (ROW(1,2,3)).*;
SELECT record_eq(ROW(1), ROW(1,2));
SELECT (ROW(1,2) < ROW(1,2,3));
SELECT '(1)'::repro.parent;
SELECT '(1,2,3)'::repro.parent;
SELECT json_populate_record(NULL::repro.parent, '{"id": "x"}');
SELECT ARRAY(SELECT ROW(1,2));
