-- Extended JSON / JSONB / jsonpath / SQL-JSON constructor errors.
SELECT jsonb_path_query('1', '$ ? (@ == )');
SELECT jsonb_path_query('1', '$.min()');
SELECT jsonb_path_query('[1,"a"]', '$.max()');
SELECT jsonb_path_query('"abc"', '$.integer()');
SELECT jsonb_path_query('"abc"', '$.number()');
SELECT jsonb_path_query('"abc"', '$.bigint()');
SELECT jsonb_path_query('"abc"', '$.decimal(2,1)');
SELECT jsonb_path_query('99', '$.decimal(2,1)');
SELECT jsonb_path_query('"2024-13-01"', '$.date()');
SELECT jsonb_path_query('"abc"', '$.timestamp()');
SELECT jsonb_path_query('{}', '$.a.b.c');
SELECT jsonb_path_query('1', '$ like_regex "("');
SELECT jsonb_path_query('"a"', '$ ? (@ starts with )');
SELECT jsonb_path_query_array('1', 'lax $.foo()');
SELECT jsonb_path_exists('1', '$ ? (1/0 > 0)');
SELECT jsonb_path_query('1', '$ + true');
SELECT jsonb_path_query('[1,2]', '$[$.size()]');
SELECT jsonb_path_query('{}', '$."a\x"');
SELECT jsonb_to_recordset('{"a":1}') AS x(a int);
SELECT jsonb_to_record('[1,2]') AS x(a int);
SELECT jsonb_populate_recordset(NULL::repro.parent, '{"id":1}');
SELECT json_object(ARRAY['a']);
SELECT json_object('{a,b}', '{1}');
SELECT jsonb_object('{a}', '{1,2}');
SELECT json_build_array(1) ->> 'x';
SELECT jsonb_set_lax('1', '{a}', NULL, true, 'nonsense');
SELECT jsonb_strip_nulls('1', true);
SELECT '5'::jsonb || '"x"'::jsonb || '[1]'::jsonb -> 'k';
SELECT jsonb_pretty('{');
SELECT jsonb_array_length('{"a":1}');
SELECT jsonb_array_length('5');
SELECT to_jsonb(1) #>> '{a}';
SELECT JSON_SCALAR('a'::text) -> 'x';
SELECT JSON_OBJECT('a': 1, 'a': 2 WITH UNIQUE);
SELECT JSON_ARRAY('a' RETURNING int);
SELECT JSON_EXISTS('1'::jsonb, '$.a' ERROR ON ERROR);
SELECT JSON_QUERY('[1,2]'::jsonb, '$[*]' WITH CONDITIONAL WRAPPER ERROR ON ERROR) ;
SELECT JSON_VALUE('{"a":1}'::jsonb, '$.a' RETURNING int4range ERROR ON ERROR);
SELECT * FROM JSON_TABLE('1'::jsonb, '$' COLUMNS (a int PATH '$.a' ERROR ON ERROR));
SELECT json_query('{}'::jsonb, '$' RETURNING bytea);
SELECT jsonb_path_query('1', '$ ? (@ >= "2020-01-01".date())');
