-- System / admin / catalog function argument and state errors.
SELECT pg_terminate_backend(0);
SELECT pg_cancel_backend(-1);
SELECT pg_terminate_backend(2147483647, -5);
SELECT pg_read_file('../../../etc/passwd');
SELECT pg_read_file('nonexistent_file_xyz');
SELECT pg_read_binary_file('/nonexistent', 0, -1);
SELECT pg_stat_file('/nonexistent_xyz');
SELECT pg_ls_dir('/nonexistent_dir_xyz');
SELECT pg_read_file('base', -1, 10);
SELECT lo_import('/nonexistent');
SELECT lo_open(999999, 131072);
SELECT loread(lo_open(0, 262144), 10);
SELECT lo_get(999999999);
SELECT lo_from_bytea(0, '\x00'::bytea) / 0;
SELECT lo_lseek(-1, 0, 0);
SELECT lo_unlink(999999999);
SELECT lo_put(999999999, 0, '\x00');
SELECT loread(-1, -1);
SELECT pg_advisory_lock(NULL);
SELECT pg_advisory_unlock(999);
SELECT set_config('nonexistent.guc', 'x', false);
SELECT set_config('shared_buffers', '1', false);
SELECT current_setting('nonexistent.setting');
SELECT current_setting('nonexistent.setting', false);
SELECT pg_get_expr('bogus', 0);
SELECT pg_get_viewdef(0);
SELECT pg_get_functiondef(0);
SELECT pg_get_constraintdef(0);
SELECT pg_relation_size('repro.nope');
SELECT pg_relation_size(999999999);
SELECT pg_relation_filenode('repro.nope');
SELECT pg_column_size(NULL) / 0;
SELECT pg_size_bytes('10 zonkabytes');
SELECT pg_size_bytes('not a size');
SELECT pg_tablespace_location(0);
SELECT pg_create_restore_point(repeat('x', 10000));
SELECT pg_switch_wal() FROM pg_is_in_recovery() WHERE pg_is_in_recovery();
SELECT pg_replication_origin_create(repeat('x', 1000));
SELECT pg_replication_origin_drop('nonexistent_origin_xyz');
SELECT pg_create_logical_replication_slot('badslot', 'nonexistent_plugin');
SELECT pg_drop_replication_slot('nonexistent_slot_xyz');
SELECT pg_create_physical_replication_slot('');
SELECT pg_export_snapshot() FROM (SELECT 1) t WHERE false;
SELECT has_table_privilege('nonexistentrole', 'repro.child', 'SELECT');
SELECT has_table_privilege('repro.child', 'NOSUCHPRIV');
SELECT has_column_privilege('repro.child', 'nosuchcol', 'SELECT');
SELECT pg_get_serial_sequence('repro.nope', 'id');
SELECT to_regclass('repro.nope') IS NULL;
SELECT '0'::regclass;
SELECT 'nonexistent_proc_xyz'::regproc;
SELECT 'nonexistent(int)'::regprocedure;
SELECT 'nonexistent'::regoperator;
SELECT 'nonexistent'::regtype;
SELECT 'nonexistent'::regrole;
SELECT 'nonexistent'::regnamespace;
SELECT 'nonexistent'::regconfig;
SELECT 'nonexistent'::regdictionary;
SELECT pg_get_object_address('nonsense', '{}', '{}');
SELECT pg_describe_object(0, 0, 0);
SELECT pg_identify_object(0, 0, 0);
