-- Query semantics: aggregates, windows, grouping sets, set ops, CTE, MERGE,
-- ON CONFLICT, LATERAL, TABLESAMPLE, subquery cardinality, RETURNING.
SELECT sum(id), label FROM repro.parent;
SELECT id FROM repro.parent GROUP BY label;
SELECT sum(sum(id)) FROM repro.parent;
SELECT count(*) FILTER (WHERE) FROM repro.parent;
SELECT rank() FROM repro.parent;
SELECT row_number() OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND UNBOUNDED PRECEDING) FROM repro.parent;
SELECT sum(id) OVER (RANGE BETWEEN 1 PRECEDING AND CURRENT ROW) FROM repro.parent;
SELECT sum(id) OVER (ORDER BY id, label RANGE 1 PRECEDING) FROM repro.parent;
SELECT lag(id, 1, 'x') OVER () FROM repro.parent;
SELECT nth_value(id, 0) OVER () FROM repro.parent;
SELECT ntile(0) OVER () FROM repro.parent;
SELECT id, count(*) OVER (PARTITION BY nosuchcol) FROM repro.parent;
SELECT percentile_cont(2) WITHIN GROUP (ORDER BY id) FROM repro.parent;
SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY label) FROM repro.parent;
SELECT array_agg(id ORDER BY id) OVER () FROM repro.parent;
SELECT 1 FROM repro.parent HAVING sum(id) > 0 GROUP BY ();
SELECT id FROM repro.parent GROUP BY GROUPING SETS ((nosuchcol));
SELECT 1 UNION SELECT 'a';
SELECT ARRAY[1] UNION SELECT ARRAY['a'];
SELECT 1 INTERSECT SELECT now();
SELECT (SELECT id FROM repro.parent);
SELECT (SELECT id, label FROM repro.parent LIMIT 1);
SELECT * FROM repro.parent WHERE id = (SELECT id FROM repro.parent);
SELECT * FROM repro.parent, LATERAL (SELECT repro.parent.id) x(a) WHERE nosuchcol;
SELECT * FROM repro.parent TABLESAMPLE bernoulli(200);
SELECT * FROM repro.parent TABLESAMPLE nosuchmethod(10);
SELECT * FROM repro.parent TABLESAMPLE system(-1);
SELECT * FROM repro.child_v TABLESAMPLE system(10);
WITH RECURSIVE t AS (SELECT 1 UNION SELECT 'a' FROM t) SELECT * FROM t;
WITH RECURSIVE t AS (SELECT * FROM t) SELECT * FROM t;
WITH t AS (SELECT 1) SELECT * FROM t, t;
WITH t AS (INSERT INTO repro.nope VALUES (1) RETURNING *) SELECT * FROM t;
INSERT INTO repro.child (id) VALUES (10) ON CONFLICT (nosuchcol) DO NOTHING;
INSERT INTO repro.child (id) VALUES (10) ON CONFLICT (id) DO UPDATE SET nosuchcol = 1;
INSERT INTO repro.child (id, parent_id, amount) VALUES (10,1,1) ON CONFLICT (id) DO UPDATE SET amount = excluded.nosuch;
MERGE INTO repro.child c USING repro.parent p ON c.id = p.id WHEN MATCHED THEN UPDATE SET nosuchcol = 1;
MERGE INTO repro.child c USING repro.parent p ON c.id = p.id WHEN MATCHED THEN INSERT VALUES (1);
MERGE INTO repro.child_v c USING repro.parent p ON true WHEN MATCHED THEN DELETE;
DELETE FROM repro.parent RETURNING nosuchcol;
UPDATE repro.parent SET id = id RETURNING sum(id);
SELECT * FROM repro.parent FOR UPDATE OF nosuchtable;
SELECT * FROM repro.parent GROUP BY id FOR UPDATE;
SELECT DISTINCT ON (label) id FROM repro.parent ORDER BY id;
SELECT id FROM repro.parent ORDER BY nosuchcol;
SELECT id AS x FROM repro.parent ORDER BY y;
VALUES (1,2), (3);
SELECT * FROM repro.parent LIMIT 'x';
SELECT * FROM repro.parent OFFSET -1 ROW;
SELECT * FROM repro.parent FETCH FIRST 0 ROWS ONLY FOR UPDATE SKIP LOCKED, (SELECT 1);
