-- More object types: trigger, rule, policy, publication, FDW, server, cast,
-- conversion, text search, statistics, generated/identity columns, event trig.
CREATE TRIGGER trg BEFORE INSERT ON repro.nope FOR EACH ROW EXECUTE FUNCTION repro.addone();
CREATE TRIGGER trg BEFORE INSERT ON repro.parent FOR EACH ROW EXECUTE FUNCTION nosuchfn();
CREATE TRIGGER trg AFTER INSERT ON repro.child_v FOR EACH ROW EXECUTE FUNCTION repro.addone();
CREATE TRIGGER trg INSTEAD OF INSERT ON repro.parent FOR EACH ROW EXECUTE FUNCTION repro.addone();
DROP TRIGGER nosuchtrg ON repro.parent;
CREATE CONSTRAINT TRIGGER ct AFTER INSERT ON repro.parent NOT DEFERRABLE INITIALLY DEFERRED FOR EACH STATEMENT EXECUTE FUNCTION repro.addone();
CREATE RULE r AS ON INSERT TO repro.nope DO NOTHING;
CREATE RULE "_RETURN" AS ON SELECT TO repro.parent DO INSTEAD SELECT 1;
DROP RULE nosuchrule ON repro.parent;
CREATE POLICY p ON repro.nope USING (true);
CREATE POLICY p ON repro.parent USING (nosuchcol > 0);
CREATE POLICY p ON repro.parent FOR nonsense USING (true);
DROP POLICY nosuchpol ON repro.parent;
ALTER TABLE repro.child_v ENABLE ROW LEVEL SECURITY;
CREATE PUBLICATION pub FOR TABLE repro.nope;
CREATE PUBLICATION pub FOR TABLE repro.child_v;
CREATE PUBLICATION pub2 FOR ALL TABLES WITH (publish = 'nonsense');
CREATE PUBLICATION pub3 FOR TABLE repro.parent WITH (publish_via_partition_root = maybe);
ALTER PUBLICATION nosuchpub ADD TABLE repro.parent;
DROP PUBLICATION nosuchpub;
CREATE SUBSCRIPTION sub CONNECTION 'host=localhost' PUBLICATION p WITH (connect=false, slot_name=NONE, create_slot=true);
CREATE SUBSCRIPTION sub2 CONNECTION 'garbagestring' PUBLICATION p WITH (connect=false, nonsense_opt=1);
DROP SUBSCRIPTION nosuchsub;
CREATE FOREIGN DATA WRAPPER fdw HANDLER nosuchfn;
CREATE FOREIGN DATA WRAPPER fdw2 OPTIONS (a 'b');
CREATE SERVER srv FOREIGN DATA WRAPPER nosuchfdw;
CREATE SERVER srv2 TYPE 'x' FOREIGN DATA WRAPPER nosuchfdw;
DROP SERVER nosuchserver;
CREATE USER MAPPING FOR public SERVER nosuchserver;
CREATE FOREIGN TABLE repro.ft (a int) SERVER nosuchserver;
CREATE CAST (int AS repro.mood) WITHOUT FUNCTION;
CREATE CAST (int AS int) WITHOUT FUNCTION;
DROP CAST (int AS nosuchtype);
CREATE CONVERSION conv FOR 'UTF8' TO 'LATIN1' FROM nosuchfn;
CREATE CONVERSION conv2 FOR 'NOSUCH' TO 'UTF8' FROM ascii_to_utf8;
CREATE TEXT SEARCH CONFIGURATION tsc (PARSER = nosuchparser);
CREATE TEXT SEARCH DICTIONARY tsd (TEMPLATE = nosuchtemplate);
ALTER TEXT SEARCH CONFIGURATION nosuchcfg ADD MAPPING FOR word WITH simple;
CREATE STATISTICS st ON nosuchcol FROM repro.parent;
CREATE STATISTICS st2 (nonsense) ON id, label FROM repro.parent;
CREATE STATISTICS st3 ON id FROM repro.parent;
CREATE EVENT TRIGGER et ON nonsense_event EXECUTE FUNCTION repro.addone();
CREATE EVENT TRIGGER et2 ON ddl_command_start EXECUTE FUNCTION nosuchfn();
CREATE TABLE repro.gen (a int, b int GENERATED ALWAYS AS (nosuchcol) STORED);
CREATE TABLE repro.gen2 (a int, b int GENERATED ALWAYS AS (a) STORED, c int GENERATED ALWAYS AS (b) STORED);
CREATE TABLE repro.idcol (a int GENERATED ALWAYS AS IDENTITY, b int GENERATED ALWAYS AS IDENTITY);
CREATE TABLE repro.idcol2 (a text GENERATED ALWAYS AS IDENTITY);
CREATE TABLE repro.excl (a int, EXCLUDE USING gist (a WITH =));
CREATE TABLE repro.excl2 (a int, EXCLUDE (a WITH &&));
