-- functioncmds, indexcmds, opclasscmds, extension, aggregate/operator DDL.
CREATE FUNCTION repro.f_badvol() RETURNS int LANGUAGE sql VOLATILE IMMUTABLE AS 'SELECT 1';
CREATE FUNCTION repro.f_dupparam(a int, a int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION repro.f_badout(OUT int, OUT int) RETURNS record LANGUAGE sql AS 'SELECT 1,2';
CREATE FUNCTION repro.f_variadic(VARIADIC int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION repro.f_defbad(a int DEFAULT 'x') RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION repro.f_defgap(a int DEFAULT 1, b int) RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION repro.f_setof() RETURNS SETOF nonexistent_type LANGUAGE sql AS 'SELECT 1';
CREATE FUNCTION repro.f_cfg() RETURNS int LANGUAGE sql SET nonexistent.guc = 'x' AS 'SELECT 1';
CREATE FUNCTION repro.f_cost() RETURNS int LANGUAGE sql COST -1 AS 'SELECT 1';
CREATE FUNCTION repro.f_rows() RETURNS int LANGUAGE sql ROWS 100 AS 'SELECT 1';
ALTER FUNCTION repro.addone(int) RENAME TO parent;
ALTER FUNCTION repro.nonexistent() OWNER TO postgres;
ALTER FUNCTION repro.addone(int) SET nonexistent.guc = 'x';
CREATE PROCEDURE repro.proc_ret() RETURNS int LANGUAGE sql AS 'SELECT 1';
CREATE AGGREGATE repro.agg_badtrans (int) (SFUNC = int4pl, STYPE = text);
CREATE AGGREGATE repro.agg_nofinal (int) (SFUNC = int4pl, STYPE = int, FINALFUNC = nonexistent);
CREATE AGGREGATE repro.agg_moving (int) (SFUNC = int4pl, STYPE = int, MSFUNC = int4pl);
CREATE AGGREGATE repro.agg_dup (int) (SFUNC = int4pl, STYPE = int);
CREATE AGGREGATE repro.agg_dup (int) (SFUNC = int4pl, STYPE = int);
CREATE OPERATOR repro.@@@ (LEFTARG = int, RIGHTARG = int, PROCEDURE = int4pl, COMMUTATOR = @@@, NONSENSE = x);
CREATE OPERATOR repro.@@@@ (PROCEDURE = int4pl);
ALTER OPERATOR repro.+(int,int) SET (RESTRICT = nonexistent);
CREATE OPERATOR CLASS repro.badopc FOR TYPE int USING btree AS OPERATOR 1 =;
CREATE OPERATOR CLASS repro.badopc2 DEFAULT FOR TYPE int USING nonexistent_am AS STORAGE int;
CREATE OPERATOR FAMILY repro.opf USING nonexistent_am;
ALTER OPERATOR FAMILY repro.nonexistent USING btree ADD OPERATOR 1 = (int,int);
CREATE INDEX ON repro.child USING nonexistent_am (amount);
CREATE INDEX ON repro.child USING btree (amount nonexistent_opclass);
CREATE INDEX ON repro.child USING hash (amount, id);
CREATE INDEX ON repro.child USING brin (amount) INCLUDE (id);
CREATE INDEX ON repro.child (amount) WHERE nosuchcol;
CREATE INDEX ON repro.child ((amount / 0));
CREATE INDEX ON repro.child (amount) WITH (fillfactor = 5000);
CREATE INDEX ON repro.child (amount COLLATE "nonexistent");
CREATE INDEX CONCURRENTLY ON repro.child (amount);
CREATE UNIQUE INDEX ON repro.child USING gin (amount);
REINDEX INDEX nonexistent_idx;
REINDEX (nonexistent_option) TABLE repro.child;
REINDEX TABLE repro.child_v;
CLUSTER repro.parent USING nonexistent_idx;
CLUSTER repro.child_v;
CREATE EXTENSION nonexistent_extension_xyz;
CREATE EXTENSION amcheck SCHEMA nonexistent_schema;
CREATE EXTENSION amcheck VERSION 'nonexistent_version';
ALTER EXTENSION nonexistent_ext UPDATE;
ALTER EXTENSION amcheck ADD TABLE repro.parent;
ALTER EXTENSION amcheck SET SCHEMA nonexistent_schema;
DROP EXTENSION nonexistent_ext;
DROP EXTENSION plpgsql;
CREATE TABLESPACE nonexistent_ts LOCATION '/nonexistent/path';
DROP TABLESPACE nonexistent_ts;
CREATE DATABASE repro_db TEMPLATE nonexistent_template;
CREATE DATABASE repro_db ENCODING 'NONSENSE';
CREATE DATABASE repro_db LOCALE_PROVIDER nonsense;
