-- plpgsql runtime errors (pl_exec.c) via DO/function bodies.
DO $$ DECLARE x int; BEGIN SELECT id FROM repro.parent INTO STRICT x; END $$;
DO $$ DECLARE x int; BEGIN SELECT id FROM repro.parent WHERE false INTO STRICT x; END $$;
DO $$ DECLARE x int; BEGIN x := (SELECT id FROM repro.parent); END $$;
DO $$ DECLARE r record; BEGIN r := ROW(1,2); RAISE NOTICE '%', r.nonexistent_field; END $$;
DO $$ DECLARE a int[]; BEGIN a[1] := 1; RAISE NOTICE '%', a['x']; END $$;
DO $$ DECLARE x int := 'notanumber'; BEGIN END $$;
DO $$ BEGIN RAISE EXCEPTION 'e' USING detail = 'd', hint = 'h', column = 'c', constraint = 'k'; END $$;
DO $$ BEGIN RAISE USING message = 'm', errcode = '22012'; END $$;
DO $$ BEGIN RAISE SQLSTATE 'ABCDE'; END $$;
DO $$ BEGIN RAISE unique_violation USING message = repeat('x',10); PERFORM 1/0; END $$;
DO $$ DECLARE c CURSOR FOR SELECT 1; BEGIN OPEN c; OPEN c; END $$;
DO $$ DECLARE c refcursor; BEGIN FETCH c INTO STRICT c; END $$;
DO $$ DECLARE c CURSOR (p int) FOR SELECT p; BEGIN OPEN c; CLOSE c; FETCH c; END $$;
DO $$ BEGIN GET DIAGNOSTICS x = ROW_COUNT; END $$;
DO $$ DECLARE n int; BEGIN GET DIAGNOSTICS n = NONEXISTENT_ITEM; END $$;
DO $$ BEGIN GET STACKED DIAGNOSTICS x = RETURNED_SQLSTATE; END $$;
DO $$ BEGIN <<a>> FOR i IN 1..2 LOOP EXIT b; END LOOP; END $$;
DO $$ BEGIN FOR i IN REVERSE 1..10 BY 0 LOOP END LOOP; END $$;
DO $$ BEGIN FOREACH i IN ARRAY 5 LOOP END LOOP; END $$;
DO $$ DECLARE x int; BEGIN FOR x IN EXECUTE 'SELECT 1,2' LOOP END LOOP; END $$;
DO $$ BEGIN EXECUTE 'SELECT $1' USING 1, 2; END $$;
DO $$ BEGIN EXECUTE 'SELET 1'; END $$;
DO $$ BEGIN EXECUTE NULL; END $$;
DO $$ DECLARE x repro.parent; BEGIN x := ROW(1); END $$;
DO $$ BEGIN ASSERT 1=2; END $$;
DO $$ BEGIN ASSERT NULL; END $$;
DO $$ BEGIN CASE WHEN false THEN NULL; END CASE; END $$;
DO $$ DECLARE x int; BEGIN CASE x WHEN 1 THEN NULL; END CASE; END $$;
DO $$ BEGIN PERFORM * FROM repro.parent; RETURN 5; END $$;
DO $$ BEGIN BEGIN PERFORM 1/0; EXCEPTION WHEN division_by_zero THEN RAISE; END; END $$;
DO $$ BEGIN RAISE division_by_zero; EXCEPTION WHEN OTHERS THEN GET STACKED DIAGNOSTICS x = PG_EXCEPTION_DETAIL; END $$;
CREATE FUNCTION repro.plf_ret() RETURNS int LANGUAGE plpgsql AS $$ BEGIN RETURN 'notanint'; END $$;
SELECT repro.plf_ret();
CREATE FUNCTION repro.plf_setof() RETURNS SETOF int LANGUAGE plpgsql AS $$ BEGIN RETURN 1; END $$;
SELECT * FROM repro.plf_setof();
CREATE FUNCTION repro.plf_noreturn() RETURNS int LANGUAGE plpgsql AS $$ BEGIN PERFORM 1; END $$;
SELECT repro.plf_noreturn();
CREATE FUNCTION repro.plf_tbl() RETURNS TABLE(a int) LANGUAGE plpgsql AS $$ BEGIN RETURN NEXT; END $$;
SELECT * FROM repro.plf_tbl();
CREATE FUNCTION repro.plf_out(OUT a int, OUT b int) LANGUAGE plpgsql AS $$ BEGIN a := 1; RETURN NEXT; END $$;
SELECT repro.plf_out();
DO $$ DECLARE x int; y int; BEGIN SELECT 1 INTO x, y; END $$;
DO $$ BEGIN NULL::int := 5; END $$;
