-- CREATE TABLE constraint transforms (parse_utilcmd.c), CTAS, matview, trigger.
CREATE TABLE repro.ct1 (a int, PRIMARY KEY (a), PRIMARY KEY (a));
CREATE TABLE repro.ct2 (a int REFERENCES repro.parent(nonexistent));
CREATE TABLE repro.ct3 (a int, FOREIGN KEY (a, nonexistent) REFERENCES repro.parent);
CREATE TABLE repro.ct4 (a int CHECK (nonexistent > 0));
CREATE TABLE repro.ct5 (a int, b int GENERATED ALWAYS AS (a) STORED PRIMARY KEY, CHECK (b > 0));
CREATE TABLE repro.ct6 (a int, EXCLUDE USING btree (a WITH &&));
CREATE TABLE repro.ct7 (a int, UNIQUE (a, a));
CREATE TABLE repro.ct8 (a int, b int, PRIMARY KEY (a, nonexistent));
CREATE TABLE repro.ct9 (a int GENERATED ALWAYS AS IDENTITY GENERATED BY DEFAULT AS IDENTITY);
CREATE TABLE repro.ct10 (a int DEFAULT 1 GENERATED ALWAYS AS (2) STORED);
CREATE TABLE repro.ct11 (a int, b int GENERATED ALWAYS AS (c) STORED, c int);
CREATE TABLE repro.ct12 (LIKE repro.nonexistent);
CREATE TABLE repro.ct13 (LIKE repro.parent INCLUDING NONSENSE);
CREATE TABLE repro.ct14 (a int) INHERITS (repro.nonexistent);
CREATE TABLE repro.ct15 (a serial, b bigserial, PRIMARY KEY (a)) PARTITION BY HASH (nonexistent);
CREATE TABLE repro.ct16 PARTITION OF repro.parent FOR VALUES IN (1);
CREATE TABLE repro.ct17 (a int) PARTITION BY LIST (a, b);
CREATE TABLE repro.ct18 (a int) WITH (nonexistent_reloption = 1);
CREATE TABLE repro.ct19 (a int) TABLESPACE nonexistent_ts;
CREATE TABLE repro.ct20 (a int) ON COMMIT DROP;   -- non-temp
CREATE UNLOGGED TABLE repro.ct21 (a int) PARTITION BY LIST (a);
CREATE TABLE repro.ct22 (a int NOT NULL NULL);
CREATE TABLE repro.ct23 (a int COLLATE "nonexistent");
CREATE TABLE repro.ct24 (a int, CONSTRAINT c CHECK (a > 0) NO INHERIT) PARTITION BY LIST (a);
CREATE TABLE repro.ct25 (a int REFERENCES repro.parent ON DELETE SET NULL (a, nonexistent));
CREATE TEMP TABLE repro.tt (a int);           -- schema-qualified temp
CREATE TABLE repro.ctas AS SELECT 1/0 AS x;
CREATE TABLE repro.parent AS SELECT 1;         -- already exists
CREATE TABLE repro.ctas2 AS SELECT * FROM repro.nonexistent;
CREATE MATERIALIZED VIEW repro.mv AS SELECT * FROM repro.nonexistent;
CREATE MATERIALIZED VIEW repro.child_v AS SELECT 1;
REFRESH MATERIALIZED VIEW repro.nonexistent_mv;
REFRESH MATERIALIZED VIEW CONCURRENTLY repro.child_v;
CREATE MATERIALIZED VIEW repro.mv2 AS SELECT 1 WITH NO DATA;
REFRESH MATERIALIZED VIEW CONCURRENTLY repro.mv2;
SELECT * FROM repro.mv2;
CREATE VIEW repro.v_agg AS SELECT count(*) FROM repro.parent;
CREATE RECURSIVE VIEW repro.rv (a) AS SELECT 1;
CREATE VIEW repro.v_check AS SELECT * FROM repro.parent WITH CHECK OPTION;
UPDATE repro.v_agg SET count = 1;
CREATE OR REPLACE VIEW repro.child_v AS SELECT id::bigint, amount FROM repro.child;
-- trigger transforms (trigger.c)
CREATE TRIGGER t1 BEFORE INSERT ON repro.parent FOR EACH ROW WHEN (OLD.id > 0) EXECUTE FUNCTION repro.addone();
CREATE TRIGGER t2 AFTER UPDATE OF nonexistent ON repro.parent EXECUTE FUNCTION repro.addone();
CREATE TRIGGER t3 BEFORE TRUNCATE ON repro.parent FOR EACH ROW EXECUTE FUNCTION repro.addone();
CREATE TRIGGER t4 AFTER INSERT ON repro.parent REFERENCING OLD TABLE AS old_rows FOR EACH ROW EXECUTE FUNCTION repro.addone();
CREATE TRIGGER t5 BEFORE INSERT ON repro.parent FOR EACH ROW EXECUTE FUNCTION repro.addone(1, 2, 3);
CREATE TRIGGER t6 AFTER INSERT ON repro.child_v FOR EACH STATEMENT EXECUTE FUNCTION repro.addone();
TRUNCATE repro.nonexistent;
TRUNCATE repro.child_v;
TRUNCATE repro.parent;   -- referenced by FK from child
