-- GRANT/REVOKE across object types (aclchk), roles (user.c), coercion/func
-- resolution (parse_coerce/parse_func), DML executor (nodeModifyTable/execMain).
GRANT SELECT ON ALL TABLES IN SCHEMA nonexistent_schema TO lowpriv;
GRANT USAGE ON SCHEMA repro TO nonexistent_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA nonexistent_schema TO lowpriv;
GRANT USAGE ON DOMAIN repro.nonexistent TO lowpriv;
GRANT USAGE ON TYPE repro.nonexistent TO lowpriv;
GRANT USAGE ON SEQUENCE repro.nonexistent_seq TO lowpriv;
GRANT USAGE ON FOREIGN DATA WRAPPER nonexistent TO lowpriv;
GRANT USAGE ON FOREIGN SERVER nonexistent TO lowpriv;
GRANT ALL ON LANGUAGE nonexistent TO lowpriv;
GRANT ALL ON LARGE OBJECT 999999999 TO lowpriv;
GRANT ALL ON TABLESPACE nonexistent TO lowpriv;
GRANT ALL ON DATABASE nonexistent TO lowpriv;
GRANT SELECT ON repro.parent TO lowpriv WITH GRANT OPTION GRANTED BY nonexistent_role;
GRANT SELECT (id, nonexistent) ON repro.parent TO lowpriv;
REVOKE GRANT OPTION FOR ALL ON repro.parent FROM lowpriv;
GRANT lowpriv TO postgres WITH ADMIN OPTION GRANTED BY nonexistent;
ALTER DEFAULT PRIVILEGES IN SCHEMA nonexistent GRANT SELECT ON TABLES TO lowpriv;
ALTER DEFAULT PRIVILEGES FOR ROLE nonexistent GRANT SELECT ON TABLES TO lowpriv;
CREATE ROLE r_conn CONNECTION LIMIT -5 LOGIN;
CREATE ROLE r_valid VALID UNTIL 'not a date';
CREATE ROLE r_dup1;
CREATE ROLE r_dup1;
ALTER ROLE postgres WITH CONNECTION LIMIT 'x';
ALTER ROLE postgres RENAME TO postgres;
ALTER ROLE nonexistent_role WITH LOGIN;
ALTER ROLE postgres SET search_path FROM CURRENT SET work_mem = '1MB';
CREATE ROLE r_mem ROLE nonexistent_role;
CREATE ROLE r_mem2 IN ROLE nonexistent_role;
CREATE ROLE r_mem3 ADMIN nonexistent_role;
DROP ROLE postgres;
SET ROLE nonexistent_role;
SET SESSION AUTHORIZATION nonexistent_role;
-- coercion / function resolution
SELECT int4(int8 '1', 2);
SELECT pg_catalog.abs();
SELECT abs(1, 2);
SELECT abs('x'::text);
SELECT nonexistent_function(1);
SELECT repro.addone(1, 2);
SELECT repro.addone(VARIADIC ARRAY[1]);
SELECT 1 OPERATOR(pg_catalog.@#$) 2;
SELECT 1 || 2 || ARRAY[3];
SELECT 'a' = 1;
SELECT ROW(1,2) = ROW(1,2,3);
SELECT NULLIF(1, 'x'::json);
SELECT COALESCE(1, 'x'::json);
SELECT GREATEST(1, 'x'::json);
SELECT CASE WHEN true THEN 1 ELSE 'x'::json END;
SELECT least(now(), 1);
SELECT (SELECT 1) IN (SELECT now());
SELECT 1 = ANY('x');
SELECT 1 = ANY(ARRAY['a']);
SELECT generate_series(1, 'x');
SELECT unnest(1);
SELECT * FROM generate_series(1,2) WITH ORDINALITY AS t(a, b, c);
-- DML executor
INSERT INTO repro.parent DEFAULT VALUES;
INSERT INTO repro.parent (id, label, id) VALUES (1, 'x', 2);
INSERT INTO repro.parent VALUES (1, 'x'), (2);
INSERT INTO repro.child_v VALUES (1, 1);
UPDATE repro.parent SET (id, label) = (1, 'x', 'y');
UPDATE repro.parent SET (id, label) = (SELECT 1);
UPDATE repro.parent SET id = DEFAULT WHERE label = 'one';
INSERT INTO repro.parent (id, label) OVERRIDING SYSTEM VALUE VALUES (5, 'x');
INSERT INTO repro.parent SELECT * FROM repro.child;
DELETE FROM repro.parent WHERE (SELECT count(*) FROM repro.parent) ;
MERGE INTO repro.parent p USING (SELECT 1 a) s ON p.id=s.a WHEN NOT MATCHED THEN INSERT (id) VALUES (s.a) WHEN NOT MATCHED THEN INSERT (id) VALUES (1);
