-- GUC session SET edge, VACUUM/ANALYZE options, subscription, misc utility.
SET search_path = 'nonexistent_schema_only';
SELECT 1;
SET row_security = maybe;
SET timezone_abbreviations = 'nonexistent_abbrev_set';
SET session_replication_role = nonsense;
SET vacuum_cost_delay = -5;
SET effective_io_concurrency = 99999999;
SET force_parallel_mode = nonsense;
SET plan_cache_mode = nonsense;
SET password_encryption = nonsense;
SET default_table_access_method = 'nonexistent_am';
SET default_toast_compression = 'nonsense';
SET synchronous_commit = maybe;
SET constraint_exclusion = nonsense;
SET log_min_duration_sample = -5;
SET backslash_quote = nonsense;
SET bytea_output = 'nonsense';
SET xmloption = nonsense;
SET transaction_isolation = 'nonsense';
SET seq_page_cost = 'x';
SET temp_buffers = '1kB';
SET application_name = E'bad\x01name';
RESET ALL;
VACUUM (FULL, FREEZE, DISABLE_PAGE_SKIPPING) repro.child_v;
VACUUM (PARALLEL -1) repro.parent;
VACUUM (PARALLEL 2, FULL) repro.parent;
VACUUM (INDEX_CLEANUP nonsense) repro.parent;
VACUUM (BUFFER_USAGE_LIMIT '1kB') repro.parent;
VACUUM (BUFFER_USAGE_LIMIT '999TB') repro.parent;
VACUUM (SKIP_DATABASE_STATS, ONLY_DATABASE_STATS) repro.parent;
VACUUM (nonexistent_option) repro.parent;
VACUUM repro.nonexistent;
VACUUM ANALYZE repro.parent (nonexistent_column);
ANALYZE (nonexistent_option) repro.parent;
ANALYZE repro.child_v;
ANALYZE repro.parent (nonexistent_col);
REINDEX (CONCURRENTLY) SYSTEM postgres;
REINDEX DATABASE nonexistent_db;
REINDEX SCHEMA nonexistent_schema;
CHECKPOINT;
CLUSTER;
CLUSTER repro.nonexistent;
DECLARE cc CURSOR WITH HOLD FOR SELECT 1;
COPY repro.parent FROM PROGRAM 'echo x';
COPY repro.parent TO STDOUT WITH (FORMAT csv, DELIMITER E'\t', NULL E'\t');
COPY repro.parent TO STDOUT WITH (FORMAT csv, QUOTE '"', ESCAPE '""');
COPY repro.parent TO STDOUT WITH (FORMAT csv, DELIMITER ',', QUOTE ',');
COPY repro.parent TO STDOUT WITH (FORMAT text, HEADER true);
COPY repro.parent TO STDOUT WITH (FORMAT csv, FORCE_QUOTE *, FORCE_NOT_NULL (id));
COPY repro.parent FROM STDIN WITH (FORMAT csv, ON_ERROR nonsense);
COPY repro.parent FROM STDIN WITH (FORMAT csv, LOG_VERBOSITY nonsense);
COPY repro.parent FROM STDIN WITH (FORMAT csv, REJECT_LIMIT 0);
COPY (UPDATE repro.parent SET id=id) TO STDOUT;
COPY binary_upgrade.nonexistent TO STDOUT;
ALTER SUBSCRIPTION nonexistent_sub ENABLE;
ALTER SUBSCRIPTION nonexistent_sub SET (nonexistent_option = 1);
ALTER SUBSCRIPTION nonexistent_sub REFRESH PUBLICATION;
CREATE PUBLICATION pub_ins FOR TABLE repro.parent WHERE (nonexistent > 0);
CREATE PUBLICATION pub_ins2 FOR TABLE repro.parent (nonexistent_col);
ALTER PUBLICATION pub_ins SET (publish = 'insert, nonsense');
SELECT xmlvalidate('<a/>'::xml, 'nonexistent');
SELECT xmlagg(1);
SELECT table_to_xml('repro.nonexistent'::regclass, true, false, '');
SELECT query_to_xml('SELET 1', true, false, '');
SELECT cursor_to_xml('nonexistent'::refcursor, 1, true, false, '');
SELECT schema_to_xml('nonexistent_schema', true, false, '');
SELECT xmltable.* FROM xmltable('/' PASSING '<a/>'::xml COLUMNS a int PATH 'nonexistent(');
