// Phase-2 parity test: the STATEFUL wasm `Scanner` handle class (generated by
// fluessig's wasm backend — ctor `build` + `scanLine` + `scanBatch` + `report`,
// compiled to wasm32) must resolve rendered log lines identically to the
// canonical Rust `Scanner` (crates/logref-scan/tests/resolve.rs is the ground
// truth). The hand-tuned TS `ScanIndex` this file originally also compared
// against is retired — the wasm scanner IS the site scanner now, and
// site/src/scanwasm.test.ts pins the site-level layer (prefix stripping +
// catch-all suppression) over it.
//
// Run: bun test crates/logref-wasm/scan.parity.test.ts   (from the repo root;
// build the nodejs-target pkg first — see README.md)

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "bun:test";

// The compiled wasm binding (wasm-bindgen --target nodejs).
import { renderSample, Scanner as WasmScanner } from "./pkg/logref_wasm.js";

type WasmHit = { site: number; literalLen: number; captures: string[] };

const REPO = join(import.meta.dir, "..", "..");
const read = (p: string) => readFileSync(join(REPO, p), "utf8");

// ── the fixture index (the Rust ground-truth corpus) ──
const FIXTURE_SITES = read("crates/logref-scan/tests/fixtures/sites.jsonl");

// A LogSite line (as stored in the index JSONL).
interface Site {
  message?: { text?: string };
}
const siteTexts = (jsonl: string): (string | undefined)[] =>
  jsonl
    .split("\n")
    .filter((l) => l.trim().length > 0)
    .map((l) => (JSON.parse(l) as Site).message?.text);

// ── 1. WASM vs Rust ground truth (must be identical) ──

// (rendered line, expected most-specific format text, expected captures) —
// transcribed verbatim from crates/logref-scan/tests/resolve.rs.
const GROUND_TRUTH: [string, string, string[]][] = [
  ['database "orders" does not exist', 'database "%s" does not exist', ["orders"]],
  [
    'could not open file "pg_wal/000000010000000000000001": No such file or directory',
    'could not open file "%s": %m',
    ["pg_wal/000000010000000000000001", "No such file or directory"],
  ],
  ["7 of 512 tuples", "%d of %d tuples", ["7", "512"]],
  ['relation "users" already exists', 'relation "%s" already exists', ["users"]],
  ["disk is 90% full", "disk is %d%% full", ["90"]],
];

test("wasm Scanner.build + report matches the Rust BuildReport", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const r = s.report();
  // resolve.rs pins: total 7, no_text 1, compiled 6, no lower/compile failures.
  expect(r.total).toBe(7);
  expect(r.noText).toBe(1);
  expect(r.compiled).toBe(6);
  expect(r.lowerFailed).toBe(0);
  expect(r.compileFailed).toBe(0);
  // i32 boundary: plain JS numbers, not BigInt.
  expect(typeof r.total).toBe("number");
});

test("wasm scanBatch top-site + captures == Rust ground truth", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const texts = siteTexts(FIXTURE_SITES);
  const lines = GROUND_TRUTH.map(([line]) => line);
  const batch = s.scanBatch(lines) as WasmHit[][];
  expect(batch.length).toBe(lines.length);

  GROUND_TRUTH.forEach(([line, expText, expCaps], i) => {
    const hits = batch[i]!;
    expect(hits.length, `no hit for ${line}`).toBeGreaterThanOrEqual(2); // specific + catch-all
    const top = hits[0]!;
    expect(texts[top.site], `wrong top site for ${line}`).toBe(expText);
    expect(top.captures, `wrong captures for ${line}`).toEqual(expCaps);
    // i32 boundary check.
    expect(typeof top.site).toBe("number");
    expect(typeof top.literalLen).toBe("number");
  });
});

test("wasm scanLine == scanBatch element-for-element", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const lines = GROUND_TRUTH.map(([line]) => line);
  const batch = s.scanBatch(lines) as WasmHit[][];
  lines.forEach((line, i) => {
    const single = s.scanLine(line) as WasmHit[];
    expect(single, `scanLine != scanBatch for ${line}`).toEqual(batch[i]!);
  });
});

test("a no-specific-site line resolves only to the bare catch-all (site 5)", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const line = "this line matches no specific site and only the bare catch-all";
  const hits = s.scanLine(line) as WasmHit[];
  expect(hits.length).toBe(1);
  expect(siteTexts(FIXTURE_SITES)[hits[0]!.site]).toBe("%s");
});

// ── 2. Larger real corpus: pg-catalog-sample.jsonl (48 sites) ──

test("larger corpus: every rendered line round-trips to its generating site", () => {
  const CORPUS = read("snippets/pg-catalog-sample.jsonl");
  const wasm = new WasmScanner(CORPUS);
  const report = wasm.report();
  console.log(
    `pg-catalog corpus: total=${report.total} compiled=${report.compiled} noText=${report.noText} lowerFailed=${report.lowerFailed} compileFailed=${report.compileFailed}`,
  );

  // Synthesize one rendered line per site with literal text (the wasm
  // renderSample is the inverse of lowering — the same canned values the Rust
  // round-trip test uses).
  const texts = siteTexts(CORPUS);
  const synth: { line: string; siteIdx: number; text: string }[] = [];
  texts.forEach((text, siteIdx) => {
    if (!text) return;
    let rendered: string;
    try {
      rendered = renderSample(text);
    } catch {
      return;
    }
    synth.push({ line: rendered, siteIdx, text });
  });
  console.log(`synthesized ${synth.length} rendered lines from the corpus`);

  const lines = synth.map((s) => s.line);
  const batch = wasm.scanBatch(lines) as WasmHit[][];

  // WASM invariant vs Rust semantics: every synthesized line must resolve to at
  // least one site, and its OWN site must be among the matches (round-trip
  // soundness — the pattern that generated the line always matches it).
  let selfMatched = 0;
  for (let i = 0; i < synth.length; i++) {
    const hits = batch[i]!;
    if (hits.some((h) => h.site === synth[i]!.siteIdx)) selfMatched++;
  }
  console.log(`round-trip: ${selfMatched}/${synth.length} lines matched their own generating site`);
  expect(selfMatched).toBe(synth.length);
});
