// Phase-2 parity test: the STATEFUL wasm `Scanner` handle class (generated by
// fluessig's wasm backend — ctor `build` + `scanLine` + `scanBatch` + `report`,
// compiled to wasm32) must resolve rendered log lines identically to the
// canonical Rust `Scanner` (crates/logref-scan/tests/resolve.rs is the ground
// truth). It is then compared against the hand-tuned TS `ScanIndex`
// (site/src/scanner.ts), whose DELIBERATE divergences (trigram prefilter, bare
// catch-alls fully excluded, `LEVEL:` prefix stripping) are documented, not
// treated as failures — the Rust/WASM scanner is ground truth.
//
// Run: bun test crates/logref-wasm/scan.parity.test.ts   (from the repo root)

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "bun:test";

// The compiled wasm binding (wasm-bindgen --target nodejs).
import { Scanner as WasmScanner } from "./pkg/logref_wasm.js";
// The hand-tuned TS scanner + its lowering (the production site surface).
import { lowerFormat, renderSample } from "../../site/src/lower.ts";
import { type PatternEntry, ScanIndex } from "../../site/src/scanner.ts";

type WasmHit = { site: number; literalLen: number; captures: string[] };

const REPO = join(import.meta.dir, "..", "..");
const read = (p: string) => readFileSync(join(REPO, p), "utf8");

// ── the fixture index + sample log (the Rust ground-truth corpus) ──
const FIXTURE_SITES = read("crates/logref-scan/tests/fixtures/sites.jsonl");
const SAMPLE_LOG = read("crates/logref-scan/tests/fixtures/sample.log")
  .split("\n")
  .filter((l) => l.length > 0);

// A LogSite line (as stored in the index JSONL).
interface Site {
  message?: { text?: string };
}
const siteTexts = (jsonl: string): (string | undefined)[] =>
  jsonl
    .split("\n")
    .filter((l) => l.trim().length > 0)
    .map((l) => (JSON.parse(l) as Site).message?.text);

/**
 * Build the TS `ScanIndex`'s `PatternEntry[]` from the SAME index JSONL the WASM
 * scanner builds from, so the two scan the same catalog. Each site's format text
 * is lowered with the production `lowerFormat`; `slug` carries the site index so
 * a TS hit can be compared to a WASM hit's `site`.
 */
function patternsFromJsonl(jsonl: string): PatternEntry[] {
  const out: PatternEntry[] = [];
  siteTexts(jsonl).forEach((text, siteIdx) => {
    if (!text) return; // no literal text (expr-only) → skipped, like Rust's no_text
    let l: ReturnType<typeof lowerFormat>;
    try {
      l = lowerFormat(text);
    } catch {
      return; // lower_failed
    }
    out.push({
      slug: String(siteIdx),
      message: text,
      level: [],
      regexSource: l.regex,
      groups: l.groups,
      literalLen: l.literalLen,
      literals: l.literals,
      catchAll: l.literals.length === 0,
    });
  });
  return out;
}

// ── 1. WASM vs Rust ground truth (must be identical) ──

// (rendered line, expected most-specific format text, expected captures) —
// transcribed verbatim from crates/logref-scan/tests/resolve.rs.
const GROUND_TRUTH: [string, string, string[]][] = [
  ['database "orders" does not exist', 'database "%s" does not exist', ["orders"]],
  [
    'could not open file "pg_wal/000000010000000000000001": No such file or directory',
    'could not open file "%s": %m',
    ["pg_wal/000000010000000000000001", "No such file or directory"],
  ],
  ["7 of 512 tuples", "%d of %d tuples", ["7", "512"]],
  ['relation "users" already exists', 'relation "%s" already exists', ["users"]],
  ["disk is 90% full", "disk is %d%% full", ["90"]],
];

test("wasm Scanner.build + report matches the Rust BuildReport", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const r = s.report();
  // resolve.rs pins: total 7, no_text 1, compiled 6, no lower/compile failures.
  expect(r.total).toBe(7);
  expect(r.noText).toBe(1);
  expect(r.compiled).toBe(6);
  expect(r.lowerFailed).toBe(0);
  expect(r.compileFailed).toBe(0);
  // i32 boundary: plain JS numbers, not BigInt.
  expect(typeof r.total).toBe("number");
});

test("wasm scanBatch top-site + captures == Rust ground truth", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const texts = siteTexts(FIXTURE_SITES);
  const lines = GROUND_TRUTH.map(([line]) => line);
  const batch = s.scanBatch(lines) as WasmHit[][];
  expect(batch.length).toBe(lines.length);

  GROUND_TRUTH.forEach(([line, expText, expCaps], i) => {
    const hits = batch[i]!;
    expect(hits.length, `no hit for ${line}`).toBeGreaterThanOrEqual(2); // specific + catch-all
    const top = hits[0]!;
    expect(texts[top.site], `wrong top site for ${line}`).toBe(expText);
    expect(top.captures, `wrong captures for ${line}`).toEqual(expCaps);
    // i32 boundary check.
    expect(typeof top.site).toBe("number");
    expect(typeof top.literalLen).toBe("number");
  });
});

test("wasm scanLine == scanBatch element-for-element", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const lines = GROUND_TRUTH.map(([line]) => line);
  const batch = s.scanBatch(lines) as WasmHit[][];
  lines.forEach((line, i) => {
    const single = s.scanLine(line) as WasmHit[];
    expect(single, `scanLine != scanBatch for ${line}`).toEqual(batch[i]!);
  });
});

test("a no-specific-site line resolves only to the bare catch-all (site 5)", () => {
  const s = new WasmScanner(FIXTURE_SITES);
  const line = "this line matches no specific site and only the bare catch-all";
  const hits = s.scanLine(line) as WasmHit[];
  expect(hits.length).toBe(1);
  expect(siteTexts(FIXTURE_SITES)[hits[0]!.site]).toBe("%s");
});

// ── 2. WASM vs the hand-tuned TS ScanIndex ──

test("wasm vs TS ScanIndex: top-site + captures agree on well-defined lines", () => {
  const wasm = new WasmScanner(FIXTURE_SITES);
  const ts = new ScanIndex(patternsFromJsonl(FIXTURE_SITES));
  const texts = siteTexts(FIXTURE_SITES);

  let agree = 0;
  const divergences: string[] = [];
  for (const [line, expText] of GROUND_TRUTH) {
    const w = wasm.scanLine(line) as WasmHit[];
    const t = ts.scanLine(line);
    // WASM top site (excluding the bare catch-all, which TS drops entirely).
    const wTop = w.find((h) => texts[h.site] !== "%s");
    const wText = wTop ? texts[wTop.site] : undefined;
    const wCaps = wTop ? wTop.captures : [];
    const tTop = t.hits[0];
    const tText = tTop?.pattern.message;
    const tCaps = tTop ? tTop.captures.map((c) => c.value) : [];
    if (wText === expText && tText === expText && JSON.stringify(wCaps) === JSON.stringify(tCaps)) {
      agree++;
    } else {
      divergences.push(`  ${JSON.stringify(line)}: wasm=${wText}/${JSON.stringify(wCaps)} ts=${tText}/${JSON.stringify(tCaps)}`);
    }
  }
  console.log(`WASM vs TS (fixture): ${agree}/${GROUND_TRUTH.length} well-defined lines agree on top-site+captures`);
  if (divergences.length > 0) console.log("divergences:\n" + divergences.join("\n"));
  expect(agree).toBe(GROUND_TRUTH.length);
});

// ── 3. Larger real corpus: pg-catalog-sample.jsonl (48 sites) ──

test("larger corpus: wasm vs Rust-shaped expectations + wasm vs TS, with counts", () => {
  const CORPUS = read("snippets/pg-catalog-sample.jsonl");
  const wasm = new WasmScanner(CORPUS);
  const report = wasm.report();
  console.log(`pg-catalog corpus: total=${report.total} compiled=${report.compiled} noText=${report.noText} lowerFailed=${report.lowerFailed} compileFailed=${report.compileFailed}`);

  // Synthesize one rendered line per site with literal text (renderSample is the
  // inverse of lowering — the same canned values the Rust round-trip test uses).
  const texts = siteTexts(CORPUS);
  const synth: { line: string; siteIdx: number; text: string }[] = [];
  texts.forEach((text, siteIdx) => {
    if (!text) return;
    const rendered = renderSample(text);
    if (rendered !== null) synth.push({ line: rendered, siteIdx, text });
  });
  console.log(`synthesized ${synth.length} rendered lines from the corpus`);

  const lines = synth.map((s) => s.line);
  const batch = wasm.scanBatch(lines) as WasmHit[][];

  // WASM invariant vs Rust semantics: every synthesized line must resolve to at
  // least one site, and its OWN site must be among the matches (round-trip
  // soundness — the pattern that generated the line always matches it).
  let selfMatched = 0;
  for (let i = 0; i < synth.length; i++) {
    const hits = batch[i]!;
    if (hits.some((h) => h.site === synth[i]!.siteIdx)) selfMatched++;
  }
  console.log(`round-trip: ${selfMatched}/${synth.length} lines matched their own generating site`);
  expect(selfMatched).toBe(synth.length);

  // WASM vs TS on the corpus: compare the top NON-catch-all site's text.
  const ts = new ScanIndex(patternsFromJsonl(CORPUS));
  let agree = 0;
  let tsEmpty = 0;
  const diffs: string[] = [];
  for (let i = 0; i < synth.length; i++) {
    const w = batch[i]!;
    const wTop = w.find((h) => texts[h.site] !== "%s");
    const wText = wTop ? texts[wTop.site] : undefined;
    const t = ts.scanLine(synth[i]!.line);
    const tText = t.hits[0]?.pattern.message;
    if (wText === tText) agree++;
    else if (t.hits.length === 0) tsEmpty++;
    else diffs.push(`  ${JSON.stringify(synth[i]!.line)}: wasm=${wText} ts=${tText}`);
  }
  console.log(`WASM vs TS (corpus): ${agree}/${synth.length} agree on top site; ${tsEmpty} TS-empty (prefilter/catch-all divergence); ${diffs.length} genuine top-site diffs`);
  if (diffs.length > 0) console.log("genuine diffs:\n" + diffs.slice(0, 15).join("\n"));
});
