// Phase-1 smoke test: the wasm `lowerFormat` (generated by fluessig's wasm
// backend, compiled to wasm32) must produce the SAME {regex, literalLen,
// specCount} as (a) the TS mirror in site/src/lower.ts and (b) the canonical
// Rust `lower_format` outputs asserted in crates/logref-core/src/scan.rs.
//
// Run: bun test crates/logref-wasm/smoke.test.ts   (from the repo root)

import { expect, test } from "bun:test";
// The compiled wasm binding (wasm-bindgen --target nodejs).
import { lowerFormat as wasmLower } from "./pkg/logref_wasm.js";
// The hand-ported TS mirror, documented byte-for-byte identical to Rust.
import { lowerFormat as tsLower } from "../../site/src/lower.ts";

type Triple = { regex: string; literalLen: number; specCount: number };
const triple = (l: { regex: string; literalLen: number; specCount: number }): Triple => ({
  regex: l.regex,
  literalLen: l.literalLen,
  specCount: l.specCount,
});

// The inputs: the ones the Rust unit tests pin, plus hex/octal/pointer specs.
const INPUTS = [
  'database "%s" does not exist',
  "disk is %d%% full",
  "%s",
  "%d of %d tuples",
  'could not open file "%s": %m',
  "value 0x%X out of range",
  "octal %o mode",
  "ptr %p here",
  "%1$s contains %2$d rows",
  "%03d",
  "%.2f",
];

// The canonical Rust outputs, transcribed from the #[test] assertions in
// crates/logref-core/src/scan.rs (regex + spec_count/literal_len where pinned).
const RUST_EXPECTED: Record<string, Partial<Triple>> = {
  'database "%s" does not exist': { regex: '^database "(.*?)" does not exist$', specCount: 1 },
  "disk is %d%% full": { regex: "^disk is (-?\\d+)% full$", specCount: 1 },
  "%s": { regex: "^(.*?)$", literalLen: 0 },
  "%d of %d tuples": { regex: "^(-?\\d+) of (-?\\d+) tuples$" },
  'could not open file "%s": %m': { regex: '^could not open file "(.*?)": (.+?)$' },
  "%1$s contains %2$d rows": { regex: "^(.*?) contains (-?\\d+) rows$" },
  "%03d": { regex: "^(-?\\d+)$" },
  "%.2f": { regex: "^([-+0-9.eEpPxXaAfFnN]+)$" },
};

test("wasm lowerFormat matches the TS mirror byte-for-byte", () => {
  for (const fmt of INPUTS) {
    const w = triple(wasmLower(fmt) as Triple);
    const t = triple(tsLower(fmt));
    expect(w, `input ${JSON.stringify(fmt)}`).toEqual(t);
    // types must be plain JS numbers, not BigInt (i32 boundary).
    expect(typeof w.literalLen).toBe("number");
    expect(typeof w.specCount).toBe("number");
  }
});

test("wasm lowerFormat matches the canonical Rust outputs", () => {
  for (const [fmt, exp] of Object.entries(RUST_EXPECTED)) {
    const w = wasmLower(fmt) as Triple;
    if (exp.regex !== undefined) expect(w.regex, `regex ${JSON.stringify(fmt)}`).toBe(exp.regex);
    if (exp.literalLen !== undefined)
      expect(w.literalLen, `literalLen ${JSON.stringify(fmt)}`).toBe(exp.literalLen);
    if (exp.specCount !== undefined)
      expect(w.specCount, `specCount ${JSON.stringify(fmt)}`).toBe(exp.specCount);
  }
});

// Also dump a table so the run is legible in CI logs.
test("dump WASM vs TS", () => {
  for (const fmt of INPUTS) {
    const w = triple(wasmLower(fmt) as Triple);
    const t = triple(tsLower(fmt));
    const ok = JSON.stringify(w) === JSON.stringify(t);
    console.log(
      `${ok ? "OK " : "DIFF"}  ${JSON.stringify(fmt).padEnd(34)} ` +
        `wasm=${JSON.stringify(w)}`,
    );
  }
});
