// Phase-1 smoke test: the wasm `lowerFormat` (generated by fluessig's wasm
// backend, compiled to wasm32) must produce the SAME lowering as the canonical
// Rust `lower_format` outputs asserted in crates/logref-core/src/scan.rs.
// (It originally also cross-checked the hand-ported TS mirror in
// site/src/lower.ts; that mirror is retired — the wasm module IS the site's
// lowering now, and site/src/scanwasm.test.ts pins the site-side behavior.)
//
// Run: bun test crates/logref-wasm/smoke.test.ts   (from the repo root; build
// the nodejs-target pkg first — see README.md)

import { expect, test } from "bun:test";
// The compiled wasm binding (wasm-bindgen --target nodejs).
import { lowerFormat as wasmLower } from "./pkg/logref_wasm.js";

type Low = {
  regex: string;
  literalLen: number;
  specCount: number;
  groups: string[];
  literals: string[];
};

// The canonical Rust outputs, transcribed from the #[test] assertions in
// crates/logref-core/src/scan.rs (fields asserted where the Rust tests pin them).
const RUST_EXPECTED: Record<string, Partial<Low>> = {
  'database "%s" does not exist': {
    regex: '^database "(.*?)" does not exist$',
    specCount: 1,
    groups: ["s"],
    literals: ['database "', '" does not exist'],
  },
  "disk is %d%% full": {
    regex: "^disk is (-?\\d+)% full$",
    specCount: 1,
    groups: ["d"],
    literals: ["disk is ", "% full"],
  },
  "%s": { regex: "^(.*?)$", literalLen: 0, groups: ["s"], literals: [] },
  "%d of %d tuples": {
    regex: "^(-?\\d+) of (-?\\d+) tuples$",
    groups: ["d", "d"],
    literals: [" of ", " tuples"],
  },
  'could not open file "%s": %m': {
    regex: '^could not open file "(.*?)": (.+?)$',
    groups: ["s", "m"],
  },
  "%1$s contains %2$d rows": { regex: "^(.*?) contains (-?\\d+) rows$" },
  "%03d": { regex: "^(-?\\d+)$" },
  "%.2f": { regex: "^([-+0-9.eEpPxXaAfFnN]+)$" },
  "value 0x%X out of range": { regex: "^value 0x([0-9a-fA-F]+) out of range$" },
  "octal %o mode": { regex: "^octal ([0-7]+) mode$" },
  "ptr %p here": { regex: "^ptr (0x[0-9a-fA-F]+|\\(nil\\)) here$" },
  "count%n done": {
    regex: "^count done$",
    specCount: 0,
    groups: [],
    literals: ["count done"],
  },
};

const KEYS = ["regex", "literalLen", "specCount", "groups", "literals"] as const;

test("wasm lowerFormat matches the canonical Rust outputs", () => {
  for (const [fmt, exp] of Object.entries(RUST_EXPECTED)) {
    const w = wasmLower(fmt) as Low;
    for (const key of KEYS) {
      if (exp[key] !== undefined)
        expect(w[key], `${key} for ${JSON.stringify(fmt)}`).toEqual(exp[key] as never);
    }
    // types must be plain JS numbers, not BigInt (i32 boundary).
    expect(typeof w.literalLen).toBe("number");
    expect(typeof w.specCount).toBe("number");
  }
});

test("wasm lowerFormat throws on dangling percent / unknown conversion", () => {
  expect(() => wasmLower("oops %")).toThrow("dangling");
  expect(() => wasmLower("%y is not real")).toThrow(
    "unknown conversion specifier '%y'",
  );
});

// Also dump a table so the run is legible in CI logs.
test("dump WASM lowering", () => {
  for (const fmt of Object.keys(RUST_EXPECTED)) {
    const w = wasmLower(fmt) as Low;
    console.log(`OK  ${JSON.stringify(fmt).padEnd(34)} wasm=${JSON.stringify(w)}`);
  }
});
