//! GENERATED by fluessig bindgen from logref.scan (api layer). Do not edit.
#![allow(clippy::all)]
#![allow(unused_imports)]

// The fixed prelude — wasm-bindgen glue; core calls are fully-qualified.
use wasm_bindgen::prelude::*;

/// A core-layer failure becomes a rejected JS value (wasm-bindgen throws it):
/// a fallible op returns `Result<_, JsValue>` and raises on `Err`.
fn err(e: impl std::fmt::Display) -> JsValue {
    JsValue::from_str(&e.to_string())
}

#[wasm_bindgen(typescript_custom_section)]
const TS_APPEND: &'static str = r#"
export interface Lowered {
  regex: string;
  literalLen: number;
  specCount: number;
}
"#;

/// A format string lowered to a regex, plus a couple of specificity signals.
/// Mirrors `logref_core::Lowered` (the `{regex, literal_len, spec_count}` core).
///
/// The counts are `i32` (fluessig `int32`) so they cross the wasm boundary as
/// plain JS numbers — `serde_wasm_bindgen` maps `i64` to `BigInt`, which would
/// break `===` against the TS mirror's `number` fields.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Lowered {
    pub regex: String,
    pub literal_len: i32,
    pub spec_count: i32,
}

/// The `Scan` contract — implement over the engine in `crate::core_impl`.
pub trait ScanCore: Sized + Send + Sync + 'static {
    fn lower_format(fmt: String) -> anyhow::Result<Lowered>;
}

/// Stateless log-line lowering/resolution helpers.
/// Lower a Postgres/C `printf`-style format string into an anchored regex.
/// Literal runs are escaped verbatim; each conversion spec becomes a capture
/// group. Fallible: a dangling `%` or an unknown conversion is rejected.
#[wasm_bindgen(js_name = "lowerFormat", unchecked_return_type = "Lowered")]
pub fn lower_format(fmt: String) -> Result<JsValue, JsValue> {
    let out = <crate::core_impl::ScanImpl as ScanCore>::lower_format(fmt).map_err(err)?;
    Ok(serde_wasm_bindgen::to_value(&out)?)
}
