//! logref-wasm — the browser (wasm32) binding for logref's `Scan` surface.
//!
//! `binding.rs` is GENERATED by `fluessig-gen --wasm` from `crates/logref-schema`
//! (run `scripts/gen.sh`); do not edit it. `core_impl.rs` is the hand-written
//! seam that implements the generated `ScanCore` trait over `logref-core`.

mod binding;
mod core_impl;

// Re-export the generated wasm-bindgen surface (the `lowerFormat` free function,
// the `Lowered` DTO) so `wasm-pack` picks it up from the crate root.
pub use binding::*;
